### ISSUE TITLE
Property useSSL does not exist on target class org.postgresql.ds.PGSimpleDataSource

### ISSUE THREAD

**Issue by Quantisan** [tomekw/hikari-cp#44]
I'm using `:use-ssl true` in `pool/make-datasource` but is getting this error below. Any pointer on how to fix this would be appreciated.

```
Caused by: java.lang.RuntimeException: Property useSSL does not exist on target class org.postgresql.ds.PGSimpleDataSource
at com.zaxxer.hikari.util.PropertyElf.setProperty(PropertyElf.java:131)
at com.zaxxer.hikari.util.PropertyElf.lambda$setTargetFromProperties$0(PropertyElf.java:57)
at java.util.Hashtable.forEach(Hashtable.java:878)
at com.zaxxer.hikari.util.PropertyElf.setTargetFromProperties(PropertyElf.java:52)
at com.zaxxer.hikari.pool.PoolBase.initializeDataSource(PoolBase.java:315)
at com.zaxxer.hikari.pool.PoolBase.<init>(PoolBase.java:108)
at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:99)
at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:71)
at hikari_cp.core$make_datasource.invokeStatic(core.clj:209)
at hikari_cp.core$make_datasource.invoke(core.clj:206)
```

My versions:

```
[hikari-cp "1.7.5"]
[org.postgresql/postgresql "9.4.1212"]
```

**Comment by Quantisan** [comment]
I ended up using `:ssl true`
